name: Main Branch CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: [main]

jobs:
  lint-typecheck:
    uses: ./.github/workflows/lint-typecheck.yml
    secrets: inherit

  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
