/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as LayoutUploadImport } from './routes/_layout.upload'
import { Route as LayoutFilesImport } from './routes/_layout.files'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutUploadRoute = LayoutUploadImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutFilesRoute = LayoutFilesImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/files': {
      id: '/_layout/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof LayoutFilesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/upload': {
      id: '/_layout/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof LayoutUploadImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutFilesRoute: typeof LayoutFilesRoute
  LayoutUploadRoute: typeof LayoutUploadRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutFilesRoute: LayoutFilesRoute,
  LayoutUploadRoute: LayoutUploadRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/files': typeof LayoutFilesRoute
  '/upload': typeof LayoutUploadRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/files': typeof LayoutFilesRoute
  '/upload': typeof LayoutUploadRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/_layout/files': typeof LayoutFilesRoute
  '/_layout/upload': typeof LayoutUploadRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/about' | '/files' | '/upload'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/about' | '/files' | '/upload'
  id:
  | '__root__'
  | '/'
  | '/_layout'
  | '/about'
  | '/_layout/files'
  | '/_layout/upload'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  AboutRoute: typeof AboutRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  AboutRoute: AboutRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout",
        "/about"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/files",
        "/_layout/upload"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/_layout/files": {
      "filePath": "_layout.files.tsx",
      "parent": "/_layout"
    },
    "/_layout/upload": {
      "filePath": "_layout.upload.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
